package.json

Provide keywords to find extension more easily #7

---

CHANGELOG.md
package-lock.json
package.json

Prepare for next iteration 0.0.2

---

CHANGELOG.md
README.md
package.json

Include WSDL 2 Camel Rest DSL extension #13

---

package-lock.json
package.json

Prepare next iteration release 0.0.3

---

README.md

Signed-off-by: mflinn <mflinn@redhat.com>

minor edit to Readme file

---

CHANGELOG.md
package-lock.json
package.json

Prepare for next iteration 0.0.4

---

Contributing.md

provide contributing.md on how to release #25

---

Contributing.md
Jenkinsfile

to allow whole team to do a release

Add whole team to submitter list #25

---

CHANGELOG.md
package.json

Update to name approved by Red Hat legal department #28

---

CHANGELOG.md
package-lock.json
package.json

Prepare next iteration 0.0.5

---

.travis.yml

Exclude dependabot branches from non-PR jobs #31

---

CHANGELOG.md
README.md
package.json

Include XML Language Support #33

---

CHANGELOG.md
package-lock.json
package.json

Prepare for next iteration 0.0.6

---

CHANGELOG.md
README.md
package.json

FUSETOOLS2-1230 - Add AtlasMap Data Transformation editor

---

CHANGELOG.md
package-lock.json
package.json

Prepare for next iteration 0.0.7

---

README.md

Fix bullet point in readme

---

CHANGELOG.md
README.md
package.json

it will makes sense to merge it when VS Code Camel K 0.0.14 will be released

FUSETOOLS2-492 - Include Didact tutorial extension

---

CHANGELOG.md
package-lock.json
package.json

Prepare next iteration development 0.0.8

---

CHANGELOG.md
package-lock.json
package.json

Prepare next development iteration 0.0.9

---

README.md

result can be seen on https://github.com/camel-tooling/vscode-camel-extension-pack/blob/54d37a259fd948595c64d15f3817e5084b9150ab/README.md

FUSETOOLS2-825 - provide Circle CI badge

---

CHANGELOG.md
package-lock.json
package.json

prepare next development iteration 0.0.11

---

CHANGELOG.md
package.json

part of Azure/vscode-kubernetes-tools#985

Add keyword for discovery of extension when using Camel Yaml DSL

---

Jenkinsfile

Remove Brian from approver list

---

CHANGELOG.md
package.json

Prepare next development iteration 0.0.13

---

CHANGELOG.md
README.md
package.json

Remove Didact which is no more maintained

---

package-lock.json

Use package-lock.json v2

---

CHANGELOG.md
package-lock.json
package.json

Prepare next iteration development 0.0.15

---

CHANGELOG.md
package-lock.json
package.json

Signed-off-by: Marcelo Henrique Diniz de Araujo <mdinizde@redhat.com>

Prepare next development iteration 0.0.18

---

.github/workflows/main.yml
.gitignore
.vscodeignore
package-lock.json
package.json
src/ui-test/tests/extension.pack.test.ts
src/ui-test/tests/extensions.installed.test.ts
src/ui-test/uitest-runner.ts
src/ui-test/utils.ts
src/ui-test/vscode-settings.json
tsconfig.json
tslint.json

FUSETOOLS2-2475: Provide test checking that all extensions from extension pack are installed/activated successfully
